### ISSUE TITLE
Вопрос. Интеграция с собственным софтом.

### ISSUE THREAD

**Issue by rinath** [percodev/api_examples#1]
Через Web API возможно ли дать команду турникету чтобы он открылся и что определенный человек прошел через него? Не смог найти в доках. Сделал собственную систему распознавания лица на питоне. Теперь осталось подключить его к турникету. Можете посоветовать как? Как я понял если турникет будет виден в локальной сети, то просто к айпи турникета обратится чтобы он открылся?

**Comment by NoboKani** [comment]
@rinath, Да, возможно, необходимо использовать API метод POST: /devices/<Идентификатор устройства>/command
Куда в body нужно передать следующее:
{
    cmdNumber: 0, // Номер исполнительного устройства
    cmdType: 0,
    cmdValue: 0, // Команда, которую необходимо отработать, могут быть: Open - 0, Controls - 1, Closed - 3
    cmdParam: -1
}
