### ISSUE TITLE
Выгрузка сотрудников с номерами пропусков

### ISSUE THREAD

**Issue by perevozchikovas** [percodev/api_examples#3]
При изучении API не нашел простого способа (одним / двумя запросами) запросить перечень сотрудников с номерами пропусков, есть ли возможность выгрузить перечень карт с привязкой к id сотрудника? Тогда можно было бы запросить отдельно перечень сотрудников и отдельно перечень пропусков, и соединить 2 набора данных, вместо того, чтобы запрашивать перечень сотрудников и потом по каждому отдельно запрашивать номера карт

**Comment by NoboKani** [comment]
@perevozchikovas, в данный момент такое невозможно, но мы учтем это и добавим в ближайшем будущем.

**Comment by perevozchikovas** [comment]
> @perevozchikovas, в данный момент такое невозможно, но мы учтем это и добавим в ближайшем будущем.

Не могли бы Вы, когда добавите соответствующий функционал, отписать здесь со ссылкой на метод?

**Comment by NoboKani** [comment]
@perevozchikovas, да, без проблем

**Comment by NoboKani** [comment]
@perevozchikovas доработали API метод (Появилось в версии 2.1.0.252 и выше) получения списка сотрудников, теперь можно передать параметр withCards=true и запрос будет возвращать список сотрудников с массивом идентификаторов.

```javascript

// Пример запроса:
const request = require('request');

const options = {
  method: 'get',
  url: 'http://ru.perco.web.com/api/users/staff/list', // ru.perco.web.com - адрес PW
  qs: {withCards: 'true'}, // Параметр необходимый для получения списка идентификаторов
  headers: {
    'Content-type': 'application/json; charset=UTF-8',
    Authorization: 'Bearer FheQfaxcXAil4dDeA1onCCEQC1LyjzdI'
  }
};

request(options, function (error, response, body) {
    if (error) throw new Error(error);

    console.log(body);
});

// Ответ будет таким
[

{
  "id": 100,
  "name":"Александров Евгений Викторович",
  "division_id": 100,
  "division_name":"ДСО",
  "user_type_id":1,
  "cards":[
      "776819"
  ],
  "photo":"/files/users/images/573775/1/small.jpeg?FheQfaxcXAil4dDeA1onCCEQC1LyjzdI&v=1617638927065"
  }
]
